app:
  base-url: ${REMOTE_APP_URL}
  security:
    secret: ${REMOTE_APP_SECRET_KEY}
    ttl:
      default: 5
      callback: 240
  editor-session:
    time-until-expiration: 15

forge:
  products:
    JIRA:
      appId: ari:cloud:ecosystem::app/${JIRA_FORGE_APP_ID}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://forge.cdn.prod.atlassian-dev.net/.well-known/jwks.json
          issuer-uri: forge/invocation-token
          audiences:
            - ${forge.products.JIRA.appId}
          principal-claim-name: principal
          principal-attribute: principal
          jwk-ttl-in-days: 20
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/onlyoffice_docs_atlassian_cloud
    username: onlyoffice
    password: onlyoffice
    hikari:
      schema: public
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS public
      connection-timeout: 10000

atlassian:
  api:
    base-url: https://api.atlassian.com