name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Forge CLI
        run: npm install -g @forge/cli
      - name: Disable Forge usage analytics
        run: forge settings set usage-analytics false
      - name: Install dependencies in Forge Root Project
        run: npm install
      - name: Install dependencies in Forge Custom UI Project
        run: npm install
        working-directory: ./static/onlyoffice-docs-jira-cloud-custom-ui
      - name: Build Forge Custom UI Project
        run: npm run build
        working-directory:  ./static/onlyoffice-docs-jira-cloud-custom-ui
      - name: Deploy Forge app
        run: forge deploy --environment production --non-interactive
        env:
          FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_APP_ID: ${{ secrets.FORGE_APP_ID }}
          FORGE_REMOTE_APP_URL: ${{ vars.FORGE_REMOTE_APP_URL }}
      - name: Get Info
        run: |
          echo "version=$(grep -Eo '[0-9]+(\.[0-9]+)+' CHANGELOG.md | head -n 1)" >> $GITHUB_OUTPUT
        id: info
      - name: Generate Changelog
        run: |
          awk '/## [0-9]/{p++} p; /## [0-9]/{if (p > 1) exit}' CHANGELOG.md | awk 'NR>2 {print last} {last=$0}' > RELEASE.md
      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          bodyFile: RELEASE.md
          tag: v${{ steps.info.outputs.version }}