name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Forge CLI
        run: npm install -g @forge/cli
      - name: Disable Forge usage analytics
        run: forge settings set usage-analytics false
      - name: Install dependencies in Forge Root Project
        run: npm install
      - name: Install dependencies in Forge Custom UI Project
        run: npm install
        working-directory: ./static/onlyoffice-docs-jira-cloud-custom-ui
      - name: Build Forge Custom UI Project
        run: npm run build
        working-directory:  ./static/onlyoffice-docs-jira-cloud-custom-ui
      - name: Deploy Forge app
        run: forge deploy --environment staging --non-interactive
        env:
          FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_APP_ID: ${{ secrets.FORGE_APP_ID }}
          FORGE_REMOTE_APP_URL: ${{ secrets.FORGE_REMOTE_APP_URL_STAGING }}
      